### ISSUE TITLE
broadcast() does not return the txid

### ISSUE THREAD

**Issue by donnlee** [bitcoinjs/regtest-client#7]
I expect `broadcast()` to return the txid, but I'm getting `null`.
Here's my code:

```
console.log('broadcasting txn.');
const bcastResp = await regtestUtils.broadcast(rawtxnHex)
console.log('response from broadcast():', bcastResp)
```

Output I see:
```
broadcasting txn.
response from broadcast(): null
```

I confirm the txn spends the coins after `regtestUtils.mine(1)`

Having the txid in the response would be very helpful because when I broadcast on testnet and mainnet those libs return the txid.

**Comment by donnlee** [comment]
I found the transaction lib I'm using (tapscript) has `getTxid()` util function, so I no longer need this from broadcast().
Though, it is surprising that broadcast() doesn't give me the txid.

**Comment by junderw** [comment]
Looks like the returned txid from the bitcoind RPC is ignored on the server side.

https://github.com/bitcoinjs/regtest-server/blob/74046f26c14ce06bad6a23552c98a4e220894650/routes/1.js#L144-L157

If you have a full transaction, you can trivially get the txid (as you have noted) so it doesn't seem too urgent.
